# Build stage
FROM node:18-alpine as build

WORKDIR /app

COPY package.json ./
# If package-lock exists, it'll use it
RUN npm install

COPY . .
RUN npm run build

# Serve stage
FROM nginx:alpine

# Copy custom Nginx configuration to handle proxying requests to the backend
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy React build
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
